#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# If you need to, you can define custom settings
# (or remove this section entirely if not relevant for you)
secret_key=$(ynh_string_random --length=50)
ynh_app_setting_set  --key=secret_key --value="$secret_key"
s3_access_key=$S3_access_key
s3_secret_key=$S3_secret_key
s3_bucket_name=$S3_bucket_name
s3_endpoint=$S3_endpoint

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"


chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."


ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template="ynh_auth.py" --destination="$install_dir/storymap/ynh_auth.py"
ynh_config_add --template="schema.sql" --destination="$install_dir/scripts/schema.sql"


#=================================================
# BUILDING APP
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir"

  python3 -m venv venv
  source venv/bin/activate
    set -a  
    source .env
    set +a
  ynh_script_progression "Installing Base dependencies..."
  ynh_hide_warnings pip install --upgrade pip wheel
  ynh_hide_warnings pip install -r requirements.txt
  deactivate

  ynh_hide_warnings ynh_exec_as_app  npm install --prefer-offline
  ynh_hide_warnings ynh_exec_as_app npm run build

  ynh_psql_execute_as_root --database="$db_name" --sql_file="$install_dir/scripts/schema.sql"

popd


#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."



# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx


ynh_config_add_systemd --service="$app" --template="$app.service"
ynh_config_add_systemd --service="$app-huey" --template="$app-huey.service"

yunohost service add "$app" --description="$app" --log="/var/log/$app/$app.log"
yunohost service add "$app-huey" --description="$app-huey" --log="/var/log/$app/$app-huey.log"


# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service="$app-huey" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
