#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================

ynh_config_remove_logrotate

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="$app-huey" --action="stop"

if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd "$app"

if ynh_hide_warnings yunohost service status "$app-huey" >/dev/null; then
    yunohost service remove "$app-huey"
fi
ynh_config_remove_systemd "$app-huey"

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
